package com.network_tech.apiHandling


interface AuctionApi {
    companion object {
        const val USER_REGISTER = "api/register"
        const val COMPLETE_PROFILE = "api/register/complete-profile"
        const val LOGIN = "api/login"
        const val CREATE_NEW_PASSWORD = "api/create-new-password"
        const val RESEND_EMAIL_LINK = "api/email/verify/resend"
        const val FORGOT_PASSWORD = "api/forgot-password"
        const val CHANGE_PASSWORD_API = "api/profile/change-password"
        const val LOGOUT_API = "api/logout"
        const val USER_UPDATE_PROFILE = "api/profile/update"
        const val GET_USER_PROFILE = "api/profile/get"
        const val GET_NOTIFICATION_COUNT = "api/notification-count"
        const val GET_VERSION = "api/versioning"
        const val USER_UPLOAD_IMAGE = "api/upload/image"
        const val FILE_UPLOAD = "/api/upload/file"
        const val USER_ADD_ADDRESS = "api/user-addresses"
        const val USER_UPDATE_ADDRESS = "api/user-addresses/update"
        const val SUBSCRIPTION_PLANS = "api/plans"

        const val USER_DELETE_ADDRESS = "api/user-addresses/{addressId}/delete"
        const val USER_PRODUCT_CATEGORIES = "api/product/data"
        const val USER_PRODUCT_SUB_CATEGORIES =
            "api/product/categories/{category_id}/sub-categories"
        const val USER_PRODUCT_GET_ATTRIBUTES = "api/product/categories/{category_id}/detail"
        const val USER_POST_PRODUCT = "api/v1/product/store"
        const val USER_HOME_LIST = "api/home"
        const val USER_RECENT_VIEWS = "api/v1/views/recent"

        const val USER_GET_ALL_PRODUCTS = "api/products"
        const val GET_SUB_CATEGORY_BY_LEVEL = "api/categories/{category_id}/list"
        const val GET_SUBSCRIPTION_DETAIL = "api/subscription-details"
        const val GET_WISH_LIST = "api/wishlist"
        const val GET_NOTIFICATION = "api/notifications"
        const val READ_ALL_NOTIFICATIONS = "api/notifications/read-all"
        const val DELETE_NOTIFICATIONS = "/api/notification/delete"
        const val ADD_REMOVE_WISH_LIST = "api/wishlist/add-remove"
        const val PRODUCT_DETAIL = "api/v1/product/{product_id}"
        const val skipVip = "api/skip"
        const val DELETE_PRODUCT = "api/product/{product_id}"
        const val USER_PROFILE_DETAIL = "api/profile/get/products"
        const val FOLLOW_USER = "api/user/follow"
        const val STORE_LISTING = "api/v1/stores"
        const val MERCHANT_DASHBOARD = "api/dashboard/merchant"
        const val FOLLOWERS_LIST_FRAGMENT = "api/user/follow/list"
        const val PLACE_UPDATE_BID = "api/auctions/bid"
        const val GET_MY_BIDS = "api/profile/my-bids"
        const val UPDATE_STATUS_PRODUCT = "/api/product/{product_id}/status"

        //      const val UPDATE_STATUS = "/api/v1/product/{product_id}/update-status"
        const val UPDATE_STATUS = "/api/v1/product/update-status"
        const val ADD_TO_CART = "api/v1/cart/add"
        const val CHECK_CART = "api/v1/cart/clear-cart"
        const val GET_CART_DATA = "api/v1/cart"
        const val GET_USER_PROMO_CODES = "api/promocodes"
        const val REMOVE_FROM_CART = "api/cart/{cart_product_id}"
        const val CHECK_PROMO_CODE = "api/cart/promocode-check"
        const val PLACE_ORDER = "api/orders"
        const val CONFIRM_ORDER = "api/orders/payment/confirm"
        const val OFFERS_LIST = "/api/v1/merchant/offers"
        const val OFFERS_LISTS = "/api/get-offer"
        const val MAKE_OFFER = "/api/make-offer"
        const val UPDATE_OFFER = "/api/update-offer"
        const val OFFERS_TOGGLE = "/api/v1/merchant/offers/status-toggle"
        const val ORDER_DETAIL = "api/orders/{order_id}"
        const val RETAILER_ORDER_DETAIL = "api/orders/{retailer_order_id}/detail"
        const val ADD_CREDITS = "api/wallet/add-credits"
        const val ORDER_RECEIVED = "api/profile/orders/received"
        const val ORDER_CANCEL = "api/orders/cancel"
        const val CONFIRM_ORDER_REQUESTS = "api/orders/{order_id}/status/update"
        const val RATE_REVIEW_PRODUCT = "api/v1/orders/reviews"
        const val GET_TRANSACTIONS = "api/profile/transactions/merchant"
        const val GET_ALL_REVIEWS = "api/orders/reviews/products/{product_id}"
        const val GET_ALL_COMMENTS = "api/product/{product_id}/reviews/{review_id}"
        const val ADD_COMMENT = "api/orders/reviews/{review_id}/comments"
        const val DELIVERY_PREFERENCES = "api/delivery/preferences"
        const val GET_ORDER_REPORTS = "api/reports/orders"
        const val GET_SALES_REVENUE_REPORT = "api/reports/sales-revenue"
        const val GET_AUCTION_CART_DETAIL = "api/cart/auction/{product_id}"
        const val AUCTION_PLACE_ORDER = "api/orders/auction/place"
        const val RETURN_PRODUCT = "api/orders/return"
        const val LIST_RETURN_PRODUCT = "api/orders/return/requests"
        const val GET_RETURN_REASONS = "api/orders/return/reasons/{category_id}"
        const val API_SEARCH = "api/search"
        const val API_GET_CATEGORY_ATTRIBUTES = "api/categories/{category_id}/filterable-attributes"
        const val API_GET_ATTRIBUTE_VALUES =
            "api/categories/{category_id}/filterable-attributes/{attribute_id}"
        const val GET_PROMOTION_RATE = "api/v1/promote/product/rate"
        const val PROMOTE_PRODUCT = "api/v1/promote/product"
        const val REQUEST_MONEY = "api/v1/wallet/request-money"
        const val BANK_LIST = "api/v1/payments/banks/list"
        const val ADD_BANK = "api/v1/payments/banks"
        const val TRACK_ORDER_API = "api/orders/{order_product_id}/tracking"
        const val RETURN_REQUEST_STATUS_CHANGE =
            "api/orders/return/requests/{return_request_id}/status-update"
        const val POST_QUERY = "/api/v1/product/{product_id}/query"
        const val POST_ANSWER = "/api/v1/product/query/answer"
        const val GET_QUERIES = "/api/v1/product/{product_id}/queries"
        const val SAVE_CARD_PREFERENCES = "/api/v1/payments/card"

        const val GET_CARD_PREFERENCES = "/api/v1/payments/list"
        const val DELETE_CARD_PREFERENCES = "/api/v1/payments/card/{card_id}"

        //    const val CHAT_MESSAGES = "/api/v1/chat/{receiver_id}/messages/{product_id}"
        const val CHAT_MESSAGES = "/api/v1/chat/{receiver_id}/messages"
        const val SUPPORT_CHAT_MESSAGES = "/api/v1/support_chat/{receiver_id}/messages"
        const val CHAT_CONVERSATIONS = "/api/v1/chat/conversations"
        const val BID_ACTION = "/api/auctions/bids/status"
        const val GET_CATEGORIES = "/api/categories/list"
        const val GET_COUNTRIES_CODE = "/api/countries"
        const val VALIDATE_EMAIL = "/api/email-validation"
        const val SERVICES_PRODUCT = "/api/services"
        const val GET_SUBSCRIPTION_PLANS = "/api/subscriptions/plans"
        const val RATE_SELLER = "/api/ratings"
        const val ADD_PRODUCT_AS_STORY = "/api/product/deals"
        const val USER_POST_REQUEST = "/api/post-requests"
        const val MY_POST_REQUEST = "/api/profile/post-requests"
        const val POST_REQUEST = "/api/post-requests/store"
        const val BLOCK_UNBLOCK = "/api/users/block"
        const val REPORT_USER = "/api/report-seller"
        const val RED_FLAGGED_DETAIL = "/api/v1/red-flag"
        const val BLACK_LIST_USERS = "/api/profile/users/blocked"
        const val VIEWS_LIST_USERS = "/api/product/story-deals/{story_id}/views"
        const val PRODUCT_FAVORITE_LIST_USERS = "/api/profile/products/{product_id}/wishlist/users"
        const val ADD_VIEW_COUNT = "/api/product/story-deals/views/update"
        const val PAYMENT_COMPLETE_PRODUCT = "/api/v1/product/payment/complete"
        const val PAYMENT_COMPLETE_SUBSCRIPTION = "/api/subscriptions/plans/payment/confirm"
        const val API_GET_FEATURED_LIST = "/api/categories/{category_id}/products/featured"
        const val USER_PRODUCT_GET_ATTRIBUTE_VALUE = "/api/categories/{category}/attributes/values"
        const val SEND_OTP = "/api/otp/send"
        const val VERIFY_OTP = "/api/otp/verify"
        const val APPLY_TRUSTED_SELLER = "/api/sellers/trusted"
        const val DELETE_CHAT = "/api/v1/chat/conversations/{chat_conversation_id}"
        const val APPLY_COUPON_CODE = "/api/v1/payments/coupons/apply"
        const val GET_ALL_POST_REQUEST_CATEGORIES = "/api/post-requests/categories"
        const val ADD_STORE = "/api/v1/stores"
        const val MY_STORE_PRODUCTS = "/api/v1/stores/{store_id}"
        const val OFFER_DETAIL = "/api/offer/{offer_id}"
        const val GET_CITIES_LIST = "/api/all-cities"
        const val CONTACT_US_API = "/api/contact-us"
        const val UPDATE_RED_FLAG = "/api/v1/product/red-flag/update"
        const val GET_CARDS = "/api/v1/card/list"
        const val CREATE_CUSTOMER = "/api/v1/creat/customer"
        const val ADD_CARD = "/api/v1/card/add"
        const val STRIPE_URL = "/api/v1/create/bankac"
        const val GET_ORDERS = "/api/orders"
        const val PAYMENT_PROCESS = "api/v1/payments/process"
        const val DELETE_PAYMENT_CARD = "/api/v1/payments/card/{payment_card_id}"

       fun getResult(): String {
            return "https://coinosh-apis.block-brew.com/api/user/version-update"
        }
    }
}